# fly.toml app configuration file for Tara UI
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tara-ui"
primary_region = "bom"  # Mumbai, change as needed

[build]
  # We'll use a Dockerfile for the build
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1 