# fly.toml app configuration file generated for tara-ui on 2025-03-19T16:47:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tara-ui'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
